/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from '../API';
type GeneratedSubscription<InputType, OutputType> = string & {
  __generatedSubscriptionInput: InputType;
  __generatedSubscriptionOutput: OutputType;
};

export const projectAdded = /* GraphQL */ `subscription ProjectAdded {
  projectAdded {
    id
    room_type {
      id
      title
      arabic_title
      english_title
      category {
        id
        title
        english_title
        description
        parent {
          id
          title
          english_title
          description
          photo
          status
          created_at
          updated_at
          filters
          __typename
        }
        photo
        status
        created_at
        updated_at
        filters
        __typename
      }
      status
      created_at
      updated_at
      photo
      __typename
    }
    is_default
    title
    status
    created_at
    updated_at
    visibility
    client_id
    client {
      id
      created_at
      updated_at
      status
      first_name
      last_name
      email
      mobile
      country_code
      gender
      type
      about_me
      my_fav_style
      my_next_style
      city_id
      country_id
      city {
        id
        created_at
        updated_at
        status
        name
        region_id
        country_id
        __typename
      }
      country {
        id
        created_at
        updated_at
        status
        name
        country_flag
        is_default
        __typename
      }
      zip
      state
      following_count
      followers_count
      followees_count
      is_followed
      total_review
      discussions_count
      comments_count
      is_verified
      is_add_gigs_tutorial_showed
      last_login
      profile_image
      facebook
      twitter
      linkedin
      blog
      project_role
      client_awards {
        id
        created_at
        updated_at
        status
        title
        code
        image
        __typename
      }
      client_badges {
        id
        created_at
        updated_at
        status
        key
        title
        value
        image
        description
        client_progress
        is_claimed
        __typename
      }
      projects {
        count
        next
        previous
        results {
          id
          is_default
          title
          status
          created_at
          updated_at
          visibility
          client_id
          discussions_count
          ideas_count
          likes_count
          shares_count
          questions_count
          description
          is_liked
          __typename
        }
        __typename
      }
      addresses {
        count
        next
        previous
        results {
          id
          name
          description
          first_name
          last_name
          phone_number
          email
          is_default
          __typename
        }
        __typename
      }
      bankcards {
        count
        next
        previous
        results {
          id
          card_type
          number
          name
          expiry_date
          partner_reference
          __typename
        }
        __typename
      }
      related_professional {
        id
        created_at
        updated_at
        client {
          id
          created_at
          updated_at
          status
          first_name
          last_name
          email
          mobile
          country_code
          gender
          type
          about_me
          my_fav_style
          my_next_style
          city_id
          country_id
          zip
          state
          following_count
          followers_count
          followees_count
          is_followed
          total_review
          discussions_count
          comments_count
          is_verified
          is_add_gigs_tutorial_showed
          last_login
          profile_image
          facebook
          twitter
          linkedin
          blog
          project_role
          sendbird_access_token
          apns_token
          balance
          is_purchased
          referral_url
          __typename
        }
        address
        categories {
          id
          title
          english_title
          description
          photo
          status
          created_at
          updated_at
          filters
          __typename
        }
        services {
          id
          created_at
          updated_at
          title
          image
          short_description
          long_description
          __typename
        }
        locations {
          id
          created_at
          updated_at
          status
          name
          region_id
          country_id
          __typename
        }
        is_profile_completed
        reviews_total
        reviews_count
        gallery_photos
        photos {
          count
          next
          previous
          __typename
        }
        is_reviewable
        projects_count
        videos {
          count
          next
          previous
          __typename
        }
        contacts {
          count
          next
          previous
          __typename
        }
        professional_type
        company_name
        company_logo
        company_registration_ref
        personal_freelance_license
        is_verified
        is_gig_professional
        gigs_count
        score
        quotations {
          count
          next
          previous
          __typename
        }
        __typename
      }
      sendbird_access_token
      apns_token
      balance
      is_purchased
      referral_url
      __typename
    }
    discussions_count
    ideas_count
    likes_count
    shares_count
    questions_count
    description
    ideas {
      id
      tag
      created_at
      updated_at
      title
      photo
      status
      source
      description
      project_id
      project {
        id
        room_type {
          id
          title
          arabic_title
          english_title
          status
          created_at
          updated_at
          photo
          __typename
        }
        is_default
        title
        status
        created_at
        updated_at
        visibility
        client_id
        client {
          id
          created_at
          updated_at
          status
          first_name
          last_name
          email
          mobile
          country_code
          gender
          type
          about_me
          my_fav_style
          my_next_style
          city_id
          country_id
          zip
          state
          following_count
          followers_count
          followees_count
          is_followed
          total_review
          discussions_count
          comments_count
          is_verified
          is_add_gigs_tutorial_showed
          last_login
          profile_image
          facebook
          twitter
          linkedin
          blog
          project_role
          sendbird_access_token
          apns_token
          balance
          is_purchased
          referral_url
          __typename
        }
        discussions_count
        ideas_count
        likes_count
        shares_count
        questions_count
        description
        ideas {
          id
          tag
          created_at
          updated_at
          title
          photo
          status
          source
          description
          project_id
          client_id
          questions_count
          shares_count
          likes_count
          is_liked
          is_photo_uploaded
          google_vision_result
          __typename
        }
        ideasList {
          count
          next
          previous
          __typename
        }
        is_liked
        collaborators {
          count
          next
          previous
          __typename
        }
        default_idea {
          id
          tag
          created_at
          updated_at
          title
          photo
          status
          source
          description
          project_id
          client_id
          questions_count
          shares_count
          likes_count
          is_liked
          is_photo_uploaded
          google_vision_result
          __typename
        }
        questions {
          count
          next
          previous
          __typename
        }
        entities {
          count
          next
          previous
          __typename
        }
        __typename
      }
      client {
        id
        created_at
        updated_at
        status
        first_name
        last_name
        email
        mobile
        country_code
        gender
        type
        about_me
        my_fav_style
        my_next_style
        city_id
        country_id
        city {
          id
          created_at
          updated_at
          status
          name
          region_id
          country_id
          __typename
        }
        country {
          id
          created_at
          updated_at
          status
          name
          country_flag
          is_default
          __typename
        }
        zip
        state
        following_count
        followers_count
        followees_count
        is_followed
        total_review
        discussions_count
        comments_count
        is_verified
        is_add_gigs_tutorial_showed
        last_login
        profile_image
        facebook
        twitter
        linkedin
        blog
        project_role
        client_awards {
          id
          created_at
          updated_at
          status
          title
          code
          image
          __typename
        }
        client_badges {
          id
          created_at
          updated_at
          status
          key
          title
          value
          image
          description
          client_progress
          is_claimed
          __typename
        }
        projects {
          count
          next
          previous
          __typename
        }
        addresses {
          count
          next
          previous
          __typename
        }
        bankcards {
          count
          next
          previous
          __typename
        }
        related_professional {
          id
          created_at
          updated_at
          address
          is_profile_completed
          reviews_total
          reviews_count
          gallery_photos
          is_reviewable
          projects_count
          professional_type
          company_name
          company_logo
          company_registration_ref
          personal_freelance_license
          is_verified
          is_gig_professional
          gigs_count
          score
          __typename
        }
        sendbird_access_token
        apns_token
        balance
        is_purchased
        referral_url
        __typename
      }
      client_id
      questions_count
      shares_count
      likes_count
      is_liked
      is_photo_uploaded
      questions {
        count
        next
        previous
        results {
          id
          created_at
          updated_at
          status
          title
          description
          idea_id
          client_id
          likes_count
          comments_count
          is_liked
          __typename
        }
        __typename
      }
      google_vision_result
      paint_colors {
        count
        next
        previous
        results {
          __typename
        }
        __typename
      }
      ideaLabels {
        count
        next
        previous
        results {
          id
          name
          related_stockrecords_count
          __typename
        }
        __typename
      }
      __typename
    }
    ideasList {
      count
      next
      previous
      results {
        id
        tag
        created_at
        updated_at
        title
        photo
        status
        source
        description
        project_id
        project {
          id
          is_default
          title
          status
          created_at
          updated_at
          visibility
          client_id
          discussions_count
          ideas_count
          likes_count
          shares_count
          questions_count
          description
          is_liked
          __typename
        }
        client {
          id
          created_at
          updated_at
          status
          first_name
          last_name
          email
          mobile
          country_code
          gender
          type
          about_me
          my_fav_style
          my_next_style
          city_id
          country_id
          zip
          state
          following_count
          followers_count
          followees_count
          is_followed
          total_review
          discussions_count
          comments_count
          is_verified
          is_add_gigs_tutorial_showed
          last_login
          profile_image
          facebook
          twitter
          linkedin
          blog
          project_role
          sendbird_access_token
          apns_token
          balance
          is_purchased
          referral_url
          __typename
        }
        client_id
        questions_count
        shares_count
        likes_count
        is_liked
        is_photo_uploaded
        questions {
          count
          next
          previous
          __typename
        }
        google_vision_result
        paint_colors {
          count
          next
          previous
          __typename
        }
        ideaLabels {
          count
          next
          previous
          __typename
        }
        __typename
      }
      __typename
    }
    is_liked
    collaborators {
      count
      next
      previous
      results {
        id
        created_at
        updated_at
        status
        first_name
        last_name
        email
        mobile
        country_code
        gender
        type
        about_me
        my_fav_style
        my_next_style
        city_id
        country_id
        city {
          id
          created_at
          updated_at
          status
          name
          region_id
          country_id
          __typename
        }
        country {
          id
          created_at
          updated_at
          status
          name
          country_flag
          is_default
          __typename
        }
        zip
        state
        following_count
        followers_count
        followees_count
        is_followed
        total_review
        discussions_count
        comments_count
        is_verified
        is_add_gigs_tutorial_showed
        last_login
        profile_image
        facebook
        twitter
        linkedin
        blog
        project_role
        client_awards {
          id
          created_at
          updated_at
          status
          title
          code
          image
          __typename
        }
        client_badges {
          id
          created_at
          updated_at
          status
          key
          title
          value
          image
          description
          client_progress
          is_claimed
          __typename
        }
        projects {
          count
          next
          previous
          __typename
        }
        addresses {
          count
          next
          previous
          __typename
        }
        bankcards {
          count
          next
          previous
          __typename
        }
        related_professional {
          id
          created_at
          updated_at
          address
          is_profile_completed
          reviews_total
          reviews_count
          gallery_photos
          is_reviewable
          projects_count
          professional_type
          company_name
          company_logo
          company_registration_ref
          personal_freelance_license
          is_verified
          is_gig_professional
          gigs_count
          score
          __typename
        }
        sendbird_access_token
        apns_token
        balance
        is_purchased
        referral_url
        __typename
      }
      __typename
    }
    default_idea {
      id
      tag
      created_at
      updated_at
      title
      photo
      status
      source
      description
      project_id
      project {
        id
        room_type {
          id
          title
          arabic_title
          english_title
          status
          created_at
          updated_at
          photo
          __typename
        }
        is_default
        title
        status
        created_at
        updated_at
        visibility
        client_id
        client {
          id
          created_at
          updated_at
          status
          first_name
          last_name
          email
          mobile
          country_code
          gender
          type
          about_me
          my_fav_style
          my_next_style
          city_id
          country_id
          zip
          state
          following_count
          followers_count
          followees_count
          is_followed
          total_review
          discussions_count
          comments_count
          is_verified
          is_add_gigs_tutorial_showed
          last_login
          profile_image
          facebook
          twitter
          linkedin
          blog
          project_role
          sendbird_access_token
          apns_token
          balance
          is_purchased
          referral_url
          __typename
        }
        discussions_count
        ideas_count
        likes_count
        shares_count
        questions_count
        description
        ideas {
          id
          tag
          created_at
          updated_at
          title
          photo
          status
          source
          description
          project_id
          client_id
          questions_count
          shares_count
          likes_count
          is_liked
          is_photo_uploaded
          google_vision_result
          __typename
        }
        ideasList {
          count
          next
          previous
          __typename
        }
        is_liked
        collaborators {
          count
          next
          previous
          __typename
        }
        default_idea {
          id
          tag
          created_at
          updated_at
          title
          photo
          status
          source
          description
          project_id
          client_id
          questions_count
          shares_count
          likes_count
          is_liked
          is_photo_uploaded
          google_vision_result
          __typename
        }
        questions {
          count
          next
          previous
          __typename
        }
        entities {
          count
          next
          previous
          __typename
        }
        __typename
      }
      client {
        id
        created_at
        updated_at
        status
        first_name
        last_name
        email
        mobile
        country_code
        gender
        type
        about_me
        my_fav_style
        my_next_style
        city_id
        country_id
        city {
          id
          created_at
          updated_at
          status
          name
          region_id
          country_id
          __typename
        }
        country {
          id
          created_at
          updated_at
          status
          name
          country_flag
          is_default
          __typename
        }
        zip
        state
        following_count
        followers_count
        followees_count
        is_followed
        total_review
        discussions_count
        comments_count
        is_verified
        is_add_gigs_tutorial_showed
        last_login
        profile_image
        facebook
        twitter
        linkedin
        blog
        project_role
        client_awards {
          id
          created_at
          updated_at
          status
          title
          code
          image
          __typename
        }
        client_badges {
          id
          created_at
          updated_at
          status
          key
          title
          value
          image
          description
          client_progress
          is_claimed
          __typename
        }
        projects {
          count
          next
          previous
          __typename
        }
        addresses {
          count
          next
          previous
          __typename
        }
        bankcards {
          count
          next
          previous
          __typename
        }
        related_professional {
          id
          created_at
          updated_at
          address
          is_profile_completed
          reviews_total
          reviews_count
          gallery_photos
          is_reviewable
          projects_count
          professional_type
          company_name
          company_logo
          company_registration_ref
          personal_freelance_license
          is_verified
          is_gig_professional
          gigs_count
          score
          __typename
        }
        sendbird_access_token
        apns_token
        balance
        is_purchased
        referral_url
        __typename
      }
      client_id
      questions_count
      shares_count
      likes_count
      is_liked
      is_photo_uploaded
      questions {
        count
        next
        previous
        results {
          id
          created_at
          updated_at
          status
          title
          description
          idea_id
          client_id
          likes_count
          comments_count
          is_liked
          __typename
        }
        __typename
      }
      google_vision_result
      paint_colors {
        count
        next
        previous
        results {
          __typename
        }
        __typename
      }
      ideaLabels {
        count
        next
        previous
        results {
          id
          name
          related_stockrecords_count
          __typename
        }
        __typename
      }
      __typename
    }
    questions {
      count
      next
      previous
      results {
        id
        created_at
        updated_at
        status
        title
        description
        idea_id
        idea {
          id
          tag
          created_at
          updated_at
          title
          photo
          status
          source
          description
          project_id
          client_id
          questions_count
          shares_count
          likes_count
          is_liked
          is_photo_uploaded
          google_vision_result
          __typename
        }
        client_id
        client {
          id
          created_at
          updated_at
          status
          first_name
          last_name
          email
          mobile
          country_code
          gender
          type
          about_me
          my_fav_style
          my_next_style
          city_id
          country_id
          zip
          state
          following_count
          followers_count
          followees_count
          is_followed
          total_review
          discussions_count
          comments_count
          is_verified
          is_add_gigs_tutorial_showed
          last_login
          profile_image
          facebook
          twitter
          linkedin
          blog
          project_role
          sendbird_access_token
          apns_token
          balance
          is_purchased
          referral_url
          __typename
        }
        likes_count
        comments_count
        is_liked
        __typename
      }
      __typename
    }
    entities {
      count
      next
      previous
      results {
        created_at
        updated_at
        status
        photo
        description
        tag
        client_id
        project_id
        entity_id
        title
        is_main_entity
        __typename
      }
      __typename
    }
    __typename
  }
}
` as GeneratedSubscription<APITypes.ProjectAddedSubscription, APITypes.ProjectAddedSubscription>;
export const serviceInqueryMessageAdded = /* GraphQL */ `subscription ServiceInqueryMessageAdded($userId: ID!) {
  serviceInqueryMessageAdded(userId: $userId) {
    userId
    has_unread_messages
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.ServiceInqueryMessageAddedSubscriptionVariables,
  APITypes.ServiceInqueryMessageAddedSubscription
>;
export const paymentStatusUpdated = /* GraphQL */ `subscription PaymentStatusUpdated($checkout_id: String!) {
  paymentStatusUpdated(checkout_id: $checkout_id) {
    checkout_id
    package_id
    status
    message
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.PaymentStatusUpdatedSubscriptionVariables,
  APITypes.PaymentStatusUpdatedSubscription
>;
export const imageProcessed = /* GraphQL */ `subscription ImageProcessed($outstandingId: ID!) {
  imageProcessed(outstandingId: $outstandingId) {
    outstandingId
    recommendedImages
    error
    __typename
  }
}
` as GeneratedSubscription<APITypes.ImageProcessedSubscriptionVariables, APITypes.ImageProcessedSubscription>;
